### ISSUE TITLE
Default Layout

### ISSUE THREAD

**Issue by niclashoyer** [RobLoach/metalsmith-jstransformer-layouts#6]
Is it possible to specify a default layout as in [metalsmith-layouts](https://github.com/superwolff/metalsmith-layouts#options), so that a file without `layout` in the header gets compiled with a layout?

**Comment by RobLoach** [comment]
That's a great idea... By default, there would be no default? How would the default layout be set? Two options:
1. In the configuration of the plugin
2. In the layout itself.... For example: `mylayout.twig`

``` html
---
defaultLayout: true
---
<html>
  <body>
    {{ contents }}
  </body>
</html>
```

Having it defined in the layout itself would keep up convention standards. Maybe allow for having it in either?

**Comment by niclashoyer** [comment]
Yes, both options seem viable. I'd like to set it in the configuration, so that I don't have to repeat the layout setting on most of my markdown files.
